#!/usr/bin/env python3
"""Auto-generate the 'Open Source Contributions' table in README.md and README.en.md.

Fetches every merged PR authored by <USER>, drops PRs merged into the user's
own repos, ranks the rest by repo stars, and rewrites the block fenced by
<!-- START: oss-contributions --> ... <!-- END: oss-contributions -->.

Star counts are rendered as live shields.io badges, so they stay current
without any workflow rewriting them.
"""
import json
import os
import re
import sys
import urllib.request

USER = os.environ.get("GH_USER", "CacinieP")
TOKEN = os.environ["GITHUB_TOKEN"]
HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "User-Agent": USER,
}
READMES = ["README.md", "README.en.md"]
MARK_START = "<!-- START: oss-contributions -->"
MARK_END = "<!-- END: oss-contributions -->"

_REPO_CACHE = {}


def api(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def fetch_repo(full):
    """Cached repo record for 'owner/repo'. None if not visible to the token."""
    if full not in _REPO_CACHE:
        try:
            _REPO_CACHE[full] = api(f"https://api.github.com/repos/{full}")
        except Exception:
            _REPO_CACHE[full] = None
    return _REPO_CACHE[full]


def fetch_stars(full):
    """Star count for 'owner/repo'. Returns 0 if unavailable."""
    repo = fetch_repo(full)
    return int(repo["stargazers_count"]) if repo else 0


def star_badge(full):
    """Live shields.io badge for owner/repo (always current, no rewrite needed)."""
    return f"[![Stars](https://img.shields.io/github/stars/{full}?style=flat-square&label=%20)](https://github.com/{full})"


def search_merged_prs():
    items, page = [], 1
    while True:
        q = f"author:{USER}+type:pr+is:merged"
        url = f"https://api.github.com/search/issues?q={q}&per_page=100&page={page}"
        data = api(url)
        items.extend(data["items"])
        if len(items) >= data["total_count"] or page >= 10:
            break
        page += 1
    return items


def main():
    repos = {}  # "owner/repo" -> {"stars": int, "prs": [(num, title, url)]}
    for it in search_merged_prs():
        parts = it.get("repository_url", "").rsplit("/", 2)
        if len(parts) < 3:
            continue
        owner, repo = parts[-2], parts[-1]
        if owner == USER:  # skip self-owned repos
            continue
        full = f"{owner}/{repo}"
        repo = fetch_repo(full)
        if repo is None or repo.get("private"):
            continue  # the profile lists open-source work only
        entry = repos.setdefault(full, {"stars": 0, "prs": []})
        entry["prs"].append((it["number"], (it.get("title") or "").strip(), it["html_url"]))

    for full, entry in repos.items():
        entry["stars"] = fetch_stars(full)

    ordered = sorted(repos.items(), key=lambda kv: kv[1]["stars"], reverse=True)
    total_prs = sum(len(e["prs"]) for _, e in ordered)

    lines = [
        "<!-- This block is auto-generated by .github/workflows/update-contributions.yml — do not edit by hand. -->",
        f"_{total_prs} merged PRs across {len(ordered)} repos · auto-updated daily._",
        "",
        "| Project | ★ | My merged PRs |",
        "|---|---|---|",
    ]
    for full, entry in ordered:
        repo = full.split("/", 1)[1]
        prs = sorted(entry["prs"])
        if len(prs) == 1:
            pr_cell = f"[#{prs[0][0]}]({prs[0][2]}) — {prs[0][1]}"
        else:
            pr_cell = " ".join(f"[#{n}]({u})" for n, _, u in prs)
        lines.append(
            f"| [**{repo}**](https://github.com/{full}) | {star_badge(full)} | {pr_cell} |"
        )

    block = "\n".join(lines)
    pattern = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.S)
    changed = False
    for readme in READMES:
        text = open(readme, encoding="utf-8").read()
        if not pattern.search(text):
            print(f"ERROR: markers not found in {readme}", file=sys.stderr)
            sys.exit(1)
        new = pattern.sub(f"{MARK_START}\n{block}\n{MARK_END}", text)
        if new != text:
            open(readme, "w", encoding="utf-8").write(new)
            changed = True

    if not changed:
        print("No changes.")
        return
    print(f"Updated: {total_prs} PRs across {len(ordered)} repos.")


if __name__ == "__main__":
    main()
