#!/usr/bin/env python3
"""Auto-generate the 'Open Source Contributions' table in README.md.

Fetches every merged PR authored by <USER>, drops PRs merged into the user's
own repos, ranks the rest by repo stars, and rewrites the block fenced by
<!-- START: oss-contributions --> ... <!-- END: oss-contributions -->.
"""
import json
import os
import re
import sys
import urllib.request

USER = os.environ.get("GH_USER", "CacinieP")
TOKEN = os.environ["GITHUB_TOKEN"]
HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "User-Agent": USER,
}
README = "README.md"
MARK_START = "<!-- START: oss-contributions -->"
MARK_END = "<!-- END: oss-contributions -->"


def api(url):
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req) as r:
        return json.load(r)


def search_merged_prs():
    items, page = [], 1
    while True:
        q = f"author:{USER}+type:pr+is:merged"
        url = f"https://api.github.com/search/issues?q={q}&per_page=100&page={page}"
        data = api(url)
        items.extend(data["items"])
        if len(items) >= data["total_count"] or page >= 10:
            break
        page += 1
    return items


def fmt_stars(n):
    return f"★{n/1000:.1f}k" if n >= 1000 else f"★{n}"


def main():
    repos = {}  # "owner/repo" -> {"stars": int, "prs": [(num, title, url)]}
    for it in search_merged_prs():
        parts = it.get("repository_url", "").rsplit("/", 2)
        if len(parts) < 3:
            continue
        owner, repo = parts[-2], parts[-1]
        if owner == USER:  # skip self-owned repos
            continue
        full = f"{owner}/{repo}"
        entry = repos.setdefault(full, {"stars": 0, "prs": []})
        entry["prs"].append((it["number"], (it.get("title") or "").strip(), it["html_url"]))

    for full, entry in repos.items():
        try:
            entry["stars"] = api(f"https://api.github.com/repos/{full}")["stargazers_count"]
        except Exception:
            pass

    ordered = sorted(repos.items(), key=lambda kv: kv[1]["stars"], reverse=True)
    total_prs = sum(len(e["prs"]) for _, e in ordered)

    lines = [
        "<!-- This block is auto-generated by .github/workflows/update-contributions.yml — do not edit by hand. -->",
        f"_{total_prs} merged PRs across {len(ordered)} repos · auto-updated daily._",
        "",
        "| Project | ★ | My merged PRs |",
        "|---|---|---|",
    ]
    for full, entry in ordered:
        repo = full.split("/", 1)[1]
        prs = sorted(entry["prs"])
        if len(prs) == 1:
            pr_cell = f"[#{prs[0][0]}]({prs[0][2]}) — {prs[0][1]}"
        else:
            pr_cell = " ".join(f"[#{n}]({u})" for n, _, u in prs)
        lines.append(
            f"| [**{repo}**](https://github.com/{full}) | {fmt_stars(entry['stars'])} | {pr_cell} |"
        )

    block = "\n".join(lines)
    text = open(README, encoding="utf-8").read()
    pattern = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.S)
    if not pattern.search(text):
        print("ERROR: markers not found in README", file=sys.stderr)
        sys.exit(1)
    new = pattern.sub(f"{MARK_START}\n{block}\n{MARK_END}", text)
    if new == text:
        print("No changes.")
        return
    open(README, "w", encoding="utf-8").write(new)
    print(f"Updated: {total_prs} PRs across {len(ordered)} repos.")


if __name__ == "__main__":
    main()
